### ISSUE TITLE
Kibana 5.1.2

### ISSUE THREAD

**Issue by HariniLebaku** [sirensolutions/kibi_radar_vis#10]
Hi,

I am getting Error after install the Radar in my kibana 5.1.2 without any error. While running kibata.bat  file i will getting error like this.

       ERROR in ../plugins/kibi_radar_vis/public/kibi_radar_vis.js
       Module not found: Error: Cannot resolve 'file' or 'directory' D:\Java\Practice\kiban
a-5.1.2-windows-x86\src\ui\public/template_vis_type/TemplateVisType in D:\Java\Practice\kib
ana-5.1.2-windows-x86\plugins\kibi_radar_vis\public
        @ ../plugins/kibi_radar_vis/public/kibi_radar_vis.js 14:34-81

**Comment by scampi** [comment]
This plugin is not yet tested with kibana 5. You can propose a PR to bring up to date ;o)

**Comment by szydan** [comment]
Hi @HariniLebaku 

There is no official release yet but you can build and install this visualisation for Kibana 5.1.2
following instructions on branch
https://github.com/sirensolutions/kibi_radar_vis/tree/branch-5.1.2

We will be releasing official releases for Kibana 5.x.x versions soon
but before I would like to fix #12
Closing this issue feel free to reopen if needed
