### ISSUE TITLE
support for 5.3.0?

### ISSUE THREAD

**Issue by RedCloudDC** [sirensolutions/kibi_radar_vis#19]
I changed package.json with current version, however, Kibana has the following error:

log   [22:02:10.725] [warning] Plugin "kibi_radar_vis" was disabled because it expected Kibana version "5.2.2", and found "5.3.0".

**Comment by szydan** [comment]
Hi @RedCloudDC 
Did you changed the **version** or the **kibana.version** parameter ?

**Comment by RedCloudDC** [comment]
yes it works however, I have a date field (contains year only) and cannot get this plugin to use the year the same as your example png. how do I use year with this chart?

**Comment by szydan** [comment]
@RedCloudDC please open a separate issue about the year problem 
Ideally with sample data and steps to reproduce it 
Thanks
