### ISSUE TITLE
Kibana 5.0

### ISSUE THREAD

**Issue by mashannon168** [sirensolutions/kibi_radar_vis#6]
Hi,

Does this support Kibana 5?

Thanks
Shannon

**Comment by scampi** [comment]
no, it was not even tested with kibana 5

**Comment by szydan** [comment]
There is no official release yet but you can build and install this visualisation for Kibana 5.0.2
following instructions on branch 
https://github.com/sirensolutions/kibi_radar_vis/tree/branch-5.x

We will be releasing official releases for Kibana 5.x.x versions soon 
but before I would like to fix https://github.com/sirensolutions/kibi_radar_vis/issues/12
Closing this issue feel free to reopen if needed
