### ISSUE TITLE
does not work with Kibana 4.6.4

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/kibi_radar_vis#7]
Hi,

**What I did :** On Kibana 4.6.4, I create a new radar, set a Terms aggregation, then define 3 metrics, and finally click on green "Play" button.

**The result :** The visualization is not rendered (blank screen on the right), and when I active my browser dev tools, I see that the AJAX query to elasticsearch works well and return json data, but then I get the following error in console :
```
Error: cols[i].aggConfig.params.field is undefined
__WEBPACK_AMD_DEFINE_RESULT__</</$scope.processTableGroups/</<@http://localhost:10235/bundles/kibana.bundle.js?v=10229:125506:14
__WEBPACK_AMD_DEFINE_RESULT__</</$scope.processTableGroups/<@http://localhost:10235/bundles/kibana.bundle.js?v=10229:125500:10
__WEBPACK_AMD_DEFINE_RESULT__</</$scope.processTableGroups@http://localhost:10235/bundles/kibana.bundle.js?v=10229:125497:8
__WEBPACK_AMD_DEFINE_RESULT__</</<@http://localhost:10235/bundles/kibana.bundle.js?v=10229:125525:14
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:10235/bundles/commons.bundle.js?v=10229:43533:24
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:10235/bundles/commons.bundle.js?v=10229:43804:14
done@http://localhost:10235/bundles/commons.bundle.js?v=10229:38253:37
completeRequest@http://localhost:10235/bundles/commons.bundle.js?v=10229:38451:8
requestLoaded@http://localhost:10235/bundles/commons.bundle.js?v=10229:38392:10

http://localhost:10235/bundles/commons.bundle.js?v=10229
Line 40184
```

**Comment by szydan** [comment]
@fbaligand  Thanks for reporting this one 
We are going to release Kibi 4.6.4 soon and fixed version kibi_radar_vis will be shipped together 
Stay tuned

**Comment by fbaligand** [comment]
Nice news !

**Comment by szydan** [comment]
Hi @fbaligand this PR https://github.com/sirensolutions/kibi_radar_vis/pull/11
was merged and should fix your issue with 4.6.4
To build the package please run 
```
npm install -g gulp
gulp package
```
You will find the *.tar.gz archive in target folder

**Comment by fbaligand** [comment]
Hi,
Thanks for the fix.

I try to package the plugin using your gulp instructions, but I got this error : 
`Error: Cannot find module 'lodash'`

Maybe you can provide the zip or tar.gz package into the [4.6.4 release](https://github.com/sirensolutions/kibi_radar_vis/releases/tag/4.6.4)

**Comment by szydan** [comment]
@fbaligand Sorry added the missing package.

**Comment by fbaligand** [comment]
@szydan 
Nice ! I just tested it => it works great with Kibana 4.6.4 !
