### ISSUE TITLE
Title of any axis

### ISSUE THREAD

**Issue by LinoOscar** [sirensolutions/kibi_radar_vis#9]
Hi Friend

I love this radar chart... thanks a lot for your effort! In kibana 5.0, the title of any axis is ever the name of the fields used in the metric configuration... you are not using title, "custom label" defined for users..

In my version i have changed line 455 in "kibi_radar_vis_controller.js" with content:
item.axis = cols[i].aggConfig.params.field.displayName;

For this if...else:
			if ((cols[i].title!=null) && (cols[i].title!=''))
				item.axis = cols[i].title;
			else
				item.axis = cols[i].aggConfig.params.field.displayName;

And solved! If it is useful for you, i'm happy to help you in so great plugin

Thanks again!
Regards,
Lino

**Comment by szydan** [comment]
Hi Lino 
Thank you so much for the hint we will use it when we release 5 compatible version

**Comment by szydan** [comment]
Hi @LinoOscar in this PR https://github.com/sirensolutions/kibi_radar_vis/pull/11 we decided to always use title which in turn will use the **customLabel**
You can try the new version by building it from master branch with 

```
npm install -g gulp 
gulp package
```
you will find the archive in target folder 

Thanks again for reporting this
